services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: sql-server-container
    environment:
      SA_PASSWORD: 'vL589%Gwd[3'
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - "mssqlsystem:/var/opt/mssql"
      - "mssqluser:/var/opt/sqlserver"

volumes:
  mssqlsystem: # external: true
  mssqluser: # external: true